### ISSUE TITLE
targeting and casting issues

### ISSUE THREAD

**Issue by TheSmellcaster** [necromancyonline/necromancy-client#7]
casting an offensive ability without a target appears to self-cast the skill, damaging yourself
similarly, having a target or not seems to make buff skills damage yourself as well
casting a heal does restore hp, but also says target took damage without actually taking the damage, unlike the other two ability types dealing real damage

replicate:
1) cast offensive ability without target and take damage
2) cast offensive ability with target and target takes damage
3) cast buff ability with or without target and take damage
4) cast heal ability and restore hp and taking "fake" damage

side note: the "damage taken" when casting a heal on another player only appears for the player receiving the healing, not the player using the healing spell

![image](https://user-images.githubusercontent.com/81120361/188060026-a86c7251-d62b-41e1-9b83-77379cfee916.png)
targeting while casting

![image](https://user-images.githubusercontent.com/81120361/188060098-f47dd411-4863-45c0-bcbf-31e3b9f00e5a.png)
the target receiving

![image](https://user-images.githubusercontent.com/81120361/188060365-ad7bf7ac-af20-4859-9054-5599f08edbf7.png)
untargeted (self) casting

**Comment by blackice36** [comment]
Already fixed in Feature-BuffSkills branch
